services:
  api_db:
    build: ./Backend/BBDD
    restart: always
    ports:
      - 3307:3306
    networks:
      - api_network
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql24
      MYSQL_PASSWORD: mysql24

  api:
    build: ./Backend/terraMarket/
    restart: always
    ports:
      - 8888:8888
    depends_on:
      - api_db
    networks:
      - api_network
    environment:
      - spring.datasource.url=jdbc:mysql://api_db:3306/terramarket_v2
      - spring.datasource.password=mysql24

  web:
    build: ./Front/terraMarket/
    restart: always
    ports:
      - 4200:4200
    depends_on:
      - api
    networks:
      - api_network

networks:
  api_network:

volumes:
  mysql-data: