INSERT INTO productos (id, nombre, imagen, idcategoria) VALUES
(1, 'Pollo entero', 'pollo_entero.jpg', 1),
(2, 'Alitas de pollo', 'alitas_pollo.jpg', 1),
(3, 'Muslos de pollo', 'muslos_pollo.jpg', 1),
(4, 'Pavo entero', 'pavo_entero.jpg', 2),
(5, 'Codorniz', 'codorniz.jpg', 3),
(6, 'Pato', 'pato.jpg', 4),
(7, 'Huevos orgánicos', 'huevos_organicos.jpg', 5),
(8, 'Huevos de gallina', 'huevos_gallina.jpg', 5),

(9, 'Filete de res', 'filete_res.jpg', 6),
(10, 'Costillas de res', 'costillas_res.jpg', 6),
(11, 'Chuletas de cerdo', 'chuletas_cerdo.jpg', 7),
(12, 'Costillas de cerdo', 'costillas_cerdo.jpg', 7),
(13, 'Carne de cordero', 'carne_cordero.jpg', 8),
(14, 'Carne de ternera', 'carne_ternera.jpg', 9),

(15, 'Jamón serrano', 'jamon_serrano.jpg', 10),
(16, 'Jamón ibérico', 'jamon_iberico.jpg', 10),
(17, 'Chorizo', 'chorizo.jpg', 11),
(18, 'Lomo embuchado', 'lomo_embuchado.jpg', 11),
(19, 'Queso manchego', 'queso_manchego.jpg', 12),
(20, 'Queso de cabra', 'queso_cabra.jpg', 12),
(21, 'Paté de hígado', 'pate_higado.jpg', 13),

(22, 'Orégano seco', 'oregano_seco.jpg', 14),
(23, 'Pimienta negra', 'pimienta_negra.jpg', 15),
(24, 'Sal marina', 'sal_marina.jpg', 16),
(25, 'Salsa de soja', 'salsa_soja.jpg', 17),
(26, 'Cilantro fresco', 'cilantro_fresco.jpg', 18),

(27, 'Manzanas', 'manzanas.jpg', 19),
(28, 'Plátanos', 'platanos.jpg', 19),
(29, 'Tomates', 'tomates.jpg', 20),
(30, 'Zanahorias', 'zanahorias.jpg', 20),
(31, 'Setas shiitake', 'setas_shiitake.jpg', 21),

(32, 'Almendras enteras', 'almendras_enteras.jpg', 22),
(33, 'Nueces peladas', 'nueces_peladas.jpg', 23),
(34, 'Pipas de girasol tostadas', 'pipas_girasol.jpg', 24),
(35, 'Semillas de chía', 'semillas_chia.jpg', 25),

(36, 'Aceite de oliva premium', 'aceite_oliva.jpg', 26),
(37, 'Trufas negras', 'trufas_negras.jpg', 26),
(38, 'Langostinos congelados', 'langostinos_congelados.jpg', 27),
(39, 'Helado de vainilla', 'helado_vainilla.jpg', 28),
(40, 'Pan de molde congelado', 'pan_molde.jpg', 29),

(41, 'Baguette', 'baguette.jpg', 30),
(42, 'Croissant', 'croissant.jpg', 31),
(43, 'Tarta de chocolate', 'tarta_chocolate.jpg', 32),
(44, 'Galletas de chocolate', 'galletas_chocolate.jpg', 33),
(45, 'Pan sin gluten', 'pan_sin_gluten.jpg', 34),

(46, 'Sandwich de jamón y queso', 'sandwich_jamon_queso.jpg', 35),
(47, 'Ensalada de pasta', 'ensalada_pasta.jpg', 36),
(48, 'Lasaña preparada', 'lasagna_preparada.jpg', 37),
(49, 'Zumo de naranja', 'zumo_naranja.jpg', 38),

(50, 'Merluza fresca', 'merluza_fresca.jpg', 39),
(51, 'Langostinos frescos', 'langostinos_frescos.jpg', 40),
(52, 'Atún en lata', 'atun_lata.jpg', 41),
(53, 'Calamares congelados', 'calamares_congelados.jpg', 42),

(54, 'Arroz jazmín', 'arroz_jazmin.jpg', 43),
(55, 'Arepas', 'arepas.jpg', 44),
(56, 'Salsa tandoori', 'salsa_tandoori.jpg', 45),

(57, 'Bacalao salado', 'bacalao_salado.jpg', 46),
(58, 'Jamón curado', 'jamon_curado.jpg', 47),
(59, 'Pepinillos en vinagre', 'pepinillos.jpg', 48),
(60, 'Aceitunas rellenas', 'aceitunas_rellenas.jpg', 49),

(61, 'Botella de agua', 'botella_agua.jpg', 50),
(62, 'Cacerola', 'cacerola.jpg', 51),
(63, 'Velas aromáticas', 'velas_aromaticas.jpg', 52),
(64, 'Otros accesorios', 'otros_accesorios.jpg', 53);
